# **チュートリアル：外部ライブラリの操作**

In this tutorial, you will learn about **imports** in Python, get some tips for working with unfamiliar libraries (and the objects they return), and dig into **operator overloading**.

このチュートリアルでは、Pythonの**import**について学習し、なじみのないライブラリ (およびそれらが返すオブジェクト) を操作するためのヒントを得て、**演算子のオーバーロードについて詳しく調べます**.

# Imports

So far we've talked about types and functions which are built-in to the language. 

But one of the best things about Python (especially if you're a data scientist) is the vast number of high-quality custom libraries that have been written for it. 

Some of these libraries are in the "standard library", meaning you can find them anywhere you run Python. Other libraries can be easily added, even if they aren't always shipped with Python.

Either way, we'll access this code with **imports**.

We'll start our example by importing `math` from the standard library.

# インポート Imports

これまで、言語に組み込まれている型と関数について説明してきました。

しかし、Pythonの優れた点の1つ (特にデータサイエンティストの場合) は、Python用に作成された高品質のカスタムライブラリが膨大にあることです。

これらのライブラリの一部は"標準ライブラリ"にあります。つまり、Pythonを実行する任意の場所で見つけることができます。その他のライブラリは、必ずしもPythonに付属していない場合でも、簡単に追加できます。

どちらの方法でも、**imports **.を使用してこのコードにアクセスします。

まず、標準ライブラリから`math`をインポートします。

In [1]:
import math

print("It's math! It has type {}".format(type(math)))

It's math! It has type <class 'module'>


`math` is a module. A module is just a collection of variables (a *namespace*, if you like) defined by someone else. We can see all the names in `math` using the built-in function `dir()`.

`math`はモジュールです。モジュールは、他のユーザーによって定義された変数(*名前空間*) のコレクションにすぎません。組み込み関数`dir () `を使って`math`の中のすべての名前を見ることができます。

In [2]:
print(dir(math))

['__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc', 'ulp']


We can access these variables using dot syntax. Some of them refer to simple values, like `math.pi`:

ドット構文を使用してこれらの変数にアクセスできます。中には`math.pi`のような単純な値を参照するものもあります。

In [3]:
print("pi to 4 significant digits = {:.4}".format(math.pi))

pi to 4 significant digits = 3.142


But most of what we'll find in the module are functions, like `math.log`:

しかし、モジュール内にあるもののほとんどは、`math.log`のような関数です。

In [4]:
math.log(32, 2)

5.0

Of course, if we don't know what `math.log` does, we can call `help()` on it:

もちろん、`math.log`が何をしているかわからない場合は、`help () `を呼び出すことができます。

In [5]:
help(math.log)

Help on built-in function log in module math:

log(...)
    log(x, [base=math.e])
    Return the logarithm of x to the given base.
    
    If the base not specified, returns the natural logarithm (base e) of x.



We can also call `help()` on the module itself. This will give us the combined documentation for *all* the functions and values in the module (as well as a high-level description of the module). Click the "output" button to see the whole `math` help page.

モジュール自体で`help () `を呼び出すこともできます。これにより、モジュール内の*すべて*の関数と値の結合されたドキュメント (およびモジュールの高レベルの説明) が得られます。`math`ヘルプページ全体を見るには、"output"ボタンをクリックしてください。

In [6]:
help(math)

Help on module math:

NAME
    math

MODULE REFERENCE
    https://docs.python.org/3.10/library/math.html
    
    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
        
        The result is between 0 and pi.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measur

### Other import syntax

If we know we'll be using functions in `math` frequently we can import it under a shorter alias to save some typing (though in this case "math" is already pretty short).

### その他のインポート構文

`math`の関数を頻繁に使用することがわかっている場合は、入力を節約するために短いエイリアスでインポートすることができます (この場合、"math"はすでにかなり短いですが) 。

In [7]:
import math as mt
mt.pi

3.141592653589793

> You may have seen code that does this with certain popular libraries like Pandas, Numpy, Tensorflow, or Matplotlib. For example, it's a common convention to `import numpy as np` and `import pandas as pd`.

> Pandas、Numpy、Tensorflow、Matplotlibなどの特定の一般的なライブラリでこれを行うコードを見たことがあるかもしれません。たとえば、`import numpy as np`と`import pandas as pd`は一般的な規則です。

The `as` simply renames the imported module. It's equivalent to doing something like:

`as`は単にインポートされたモジュールの名前を変更するだけです。これは、次のように実行することと同じです。

In [8]:
import math
mt = math

Wouldn't it be great if we could refer to all the variables in the `math` module by themselves? i.e. if we could just refer to `pi` instead of `math.pi` or `mt.pi`? Good news: we can do that.

`math`モジュール内のすべての変数を単独で参照できたら素晴らしいと思いませんか?つまり、`math.pi`や`mt.pi`の代わりに`pi`を参照することができれば?朗報ですそれは可能です。

In [9]:
from math import *
print(pi, log(32, 2))

3.141592653589793 5.0


`import *` makes all the module's variables directly accessible to you (without any dotted prefix).

Bad news: some purists might grumble at you for doing this.

Worse: they kind of have a point.

`import *`を使用すると、モジュールのすべての変数に直接アクセスできます (ドット付きの接頭辞なし) 。

悪いニュース:一部の純粋主義者は、あなたがこれをすることに不平を言うかもしれません。

さらに悪いことに、彼らには一理ある。

In [10]:
from math import *
from numpy import *
print(pi, log(32, 2))

TypeError: return arrays must be of ArrayType

What has happened? It worked before!

These kinds of "star imports" can occasionally lead to weird, difficult-to-debug situations.

The problem in this case is that the `math` and `numpy` modules both have functions called `log`, but they have different semantics. Because we import from `numpy` second, its `log` overwrites (or "shadows") the `log` variable we imported from `math`.

A good compromise is to import only the specific things we'll need from each module:

何があったんですか?前はうまくいったのに!

この種の"スターインポート"は、奇妙でデバッグが困難な状況につながることがあります。

この場合の問題は、`math`モジュールと`numpy`モジュールはどちらも`log`という関数を持っていますが、それらは異なる意味を持っています。`numpy`secondからインポートするため、その`log`は`math`からインポートした`log`変数を上書き (または"シャドウ") します。

良い妥協案は、各モジュールから必要な特定のものだけをインポートすることです。

In [23]:
from math import log, pi
from numpy import asarray

### Submodules

We've seen that modules contain variables which can refer to functions or values. Something to be aware of is that they can also have variables referring to *other modules*. 

### サブモジュール

モジュールには、関数や値を参照できる変数が含まれています。注意しなければならないのは、他のモジュールを参照する変数を持つこともできるということです。

In [12]:
import numpy
print("numpy.random is a", type(numpy.random))
print("it contains names such as...",
      dir(numpy.random)[-15:]
     )

numpy.random is a <class 'module'>
it contains names such as... ['set_bit_generator', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uniform', 'vonmises', 'wald', 'weibull', 'zipf']


So if we import `numpy` as above, then calling a function in the `random` "submodule" will require *two* dots.

したがって、上記のように`numpy`をインポートすると、`random`"サブモジュール"内の関数を呼び出すには*2*個のドットが必要になります。

In [13]:
# 10個のサイコロを振る
rolls = numpy.random.randint(low=1, high=6, size=10)
rolls

array([1, 3, 5, 2, 2, 2, 1, 4, 5, 2])

## Oh the places you'll go, oh the objects you'll see

So after 6 lessons, you're a pro with ints, floats, bools, lists, strings, and dicts (right?). 

Even if that were true, it doesn't end there. As you work with various libraries for specialized tasks, you'll find that they define their own types which you'll have to learn to work with. For example, if you work with the graphing library `matplotlib`, you'll be coming into contact with objects it defines which represent Subplots, Figures, TickMarks, and Annotations. `pandas` functions will give you DataFrames and Series. 

In this section, I want to share with you a quick survival guide for working with strange types.

## Three tools for understanding strange objects

In the cell above, we saw that calling a `numpy` function gave us an "array". We've never seen anything like this before (not in this course anyways). But don't panic: we have three familiar builtin functions to help us here.

**1: `type()`** (what is this thing?)

## ああ、あなたが行く場所、ああ、あなたが見るもの

6回のレッスンを受ければ、int、float、bool、list、string、dictのプロになれます。) 。

それが本当だとしても、それだけでは終わらない。特殊なタスクのためにさまざまなライブラリーを使用すると、ライブラリーが独自の型を定義していることに気づくでしょう。たとえば、グラフ作成ライブラリ`matplotlib`を使用する場合、このライブラリで定義されているSubplots、Figures、TickMarks、Annotationsを表すオブジェクトを使用することになります。`pandas`関数はDataFrameとSeriesを提供します。

このセクションでは、奇妙な型を扱うための簡単なサバイバルガイドを共有したいと思います。

# 奇妙な物体を理解するための3つのツール

上のセルでは、"numpy"関数を呼び出すと"array"が得られます。このようなものはこれまで見たことがありません (このコースではありません) 。しかし、慌てることはありません。3つの使い慣れた組み込み関数があります。

**1:`type () `**(これは何だ?)

In [14]:
type(rolls)

numpy.ndarray

**2: `dir()`** (what can I do with it?)

**2:`dir () `**(どうすればいいのか?)

In [15]:
print(dir(rolls))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '

In [17]:
# 平均的な展開が必要な場合は、"mean"メソッドが有望です...。
rolls.mean()

2.7

In [18]:
# あるいは、単に配列をリストにしたいだけかもしれません。その場合は"tolist"を使うことができます。
rolls.tolist()

[1, 3, 5, 2, 2, 2, 1, 4, 5, 2]

**3: `help()`** (tell me more)

**3:`help () `** (もっと教えて)

In [19]:
#"ravel"属性は興味深いですね。私はクラシック音楽の大ファンです。
help(rolls.ravel)

Help on built-in function ravel:

ravel(...) method of numpy.ndarray instance
    a.ravel([order])
    
    Return a flattened array.
    
    Refer to `numpy.ravel` for full documentation.
    
    See Also
    --------
    numpy.ravel : equivalent function
    
    ndarray.flat : a flat iterator on the array.



In [20]:
# では、numpy.ndarrayについて知っておくべきことをすべて教えてください。(「出力」ボタンをクリックすると、novel-length出力が表示されます) 。
help(rolls)

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

(Of course, you might also prefer to check out [the online docs](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.ndarray.html).)

(もちろん、[オンラインドキュメント](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.ndarray.html) も参照してください。)

### Operator overloading

What's the value of the below expression?

### 演算子のオーバーロード

次の式の値は?

In [21]:
[3, 4, 1, 2, 2, 1] + 10

TypeError: can only concatenate list (not "int") to list

What a silly question. Of course it's an error. 

But what about...

なんてばかげた質問なんでしょう。もちろんエラーです。

でも...

In [22]:
rolls + 10

array([11, 13, 15, 12, 12, 12, 11, 14, 15, 12])

We might think that Python strictly polices how pieces of its core syntax behave such as `+`, `<`, `in`, `==`, or square brackets for indexing and slicing. But in fact, it takes a very hands-off approach. When you define a new type, you can choose how addition works for it, or what it means for an object of that type to be equal to something else.

The designers of lists decided that adding them to numbers wasn't allowed. The designers of `numpy` arrays went a different way (adding the number to each element of the array).

Here are a few more examples of how `numpy` arrays interact unexpectedly with Python operators (or at least differently from lists).

Pythonは、`+`、`<`、`in`、`==`、あるいはインデックスやスライスのための角括弧など、コア構文の各部の振る舞いを厳密に規定していると考えるかもしれません。しかし、実際には、非常に干渉的なアプローチを取っています。新しい型を定義するときに、加算の動作方法や、その型のオブジェクトが他のものと等しいことの意味を選択できます。

リストの設計者は、リストを数値に追加することは許可されないと判断しました。`numpy`配列の設計者は別の方法を取りました (配列の各要素に数値を追加します) 。

ここでは、`numpy`配列がどのようにPython演算子と予期せず (あるいは少なくともリストとは異なる) 相互作用するかについて、さらにいくつかの例を示します。

In [28]:
# どのインデックスでサイコロが3以下になりますか?
rolls <= 3

array([ True,  True, False,  True,  True,  True,  True, False, False,
        True])

In [34]:
xlist = [[1,2,3],[2,4,6],]
# 2次元配列を作成 Create a 2-dimensional array
x = numpy.asarray(xlist)
print("xlist = {}\nx =\n{}".format(xlist, x))

xlist = [[1, 2, 3], [2, 4, 6]]
x =
[[1 2 3]
 [2 4 6]]


In [42]:
# numpy配列の2行目の最後の要素を取得する
x[1, -1]

numpy.ndarray

In [52]:
# 入れ子リストの2番目のサブリストの最後の要素を取得する?
xlist[1][2]

6

numpy's `ndarray` type is specialized for working with multi-dimensional data, so it defines its own logic for indexing, allowing us to index by a tuple to specify the index at each dimension.

### When does 1 + 1 not equal 2?

Things can get weirder than this. You may have heard of (or even used) tensorflow, a Python library popularly used for deep learning. It makes extensive use of operator overloading.

numpyの`ndarray`型は多次元データの操作に特化しているため、インデックス付けのための独自のロジックを定義し、各次元でインデックスを指定するためにタプルでインデックスを付けることができます。

### 1+1が2と等しくないのはどのような場合ですか?

事態はもっと奇妙になることがあります。深層学習によく使用されるPythonライブラリであるtensorflowについては、聞いたことがある (または使用したことがある) かもしれません。演算子のオーバーロードを多用します。

In [53]:
import tensorflow as tf
# 値が1の2つの定数を作成します。
a = tf.constant(1)
b = tf.constant(1)
# これらを加算して...
a + b

2024-04-24 15:57:16.257508: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-04-24 15:57:16.257660: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-04-24 15:57:16.426534: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


<tf.Tensor: shape=(), dtype=int32, numpy=2>

`a + b` isn't 2, it is (to quote tensorflow's documentation)...

> a symbolic handle to one of the outputs of an `Operation`. It does not hold the values of that operation's output, but instead provides a means of computing those values in a TensorFlow `tf.Session`.



`a+b`は2ではなく、(tensorflowのドキュメントを引用すると) ...

> `Operation`の出力の1つへのシンボリックハンドル。

その操作の出力の値を保持するのではなく、TensorFlow `tf.Session`です。



It's important just to be aware of the fact that this sort of thing is possible and that libraries will often use operator overloading in non-obvious or magical-seeming ways.

Understanding how Python's operators work when applied to ints, strings, and lists is no guarantee that you'll be able to immediately understand what they do when applied to a tensorflow `Tensor`, or a numpy `ndarray`, or a pandas `DataFrame`.

Once you've had a little taste of DataFrames, for example, an expression like the one below starts to look appealingly intuitive:

```python
# Get the rows with population over 1m in South America
df[(df['population'] > 10**6) & (df['continent'] == 'South America')]
```

But why does it work? The example above features something like **5** different overloaded operators. What's each of those operations doing? It can help to know the answer when things start going wrong.

重要なのは、このようなことが可能であるという事実と、ライブラリがわかりにくい方法や魔法のような方法で演算子のオーバーロードを使用することが多いという事実を認識することです。

Pythonの演算子がint、string、およびlistに適用されたときにどのように動作するかを理解しても、tensorflow`Tensor`、numpy`ndarray`、またはpandas`DataFrame`に適用されたときに何をするかをすぐに理解できる保証はありません。

たとえば、DataFramesを少し試してみると、次のような式が直感的に見えてきます。

```python
# 南アメリカの人口が1mを超える行を取得します。
df[(df['population'] > 10**6) & (df['continent'] == 'South America')]
```
しかし、なぜ効果があるのでしょうか?上記の例は、**5**のような異なるオーバーロードされた演算子を特徴としています。それぞれの操作は何をしているのでしょうか?物事がうまくいかなくなったときに、答えを知っておくと役に立つことがあります。

#### Curious how it all works?

Have you ever called `help()` or `dir()` on an object and wondered what the heck all those names with the double-underscores were?

#### どのように動作するのか興味がありますか?

オブジェクトに対して`help () `や`dir () `をコールして、二重アンダースコアの付いた名前は一体何なんだろうと思ったことはありませんか?

In [54]:
print(dir(list))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


This turns out to be directly related to operator overloading.

When Python programmers want to define how operators behave on their types, they do so by implementing methods with special names beginning and ending with 2 underscores such as `__lt__`, `__setattr__`, or `__contains__`. Generally, names that follow this double-underscore format have a special meaning to Python.

So, for example, the expression `x in [1, 2, 3]` is actually calling the list method `__contains__` behind-the-scenes. It's equivalent to (the much uglier) `[1, 2, 3].__contains__(x)`. 

If you're curious to learn more, you can check out [Python's official documentation](https://docs.python.org/3.4/reference/datamodel.html#special-method-names), which describes many, many more of these special "underscores" methods.

We won't be defining our own types in these lessons (if only there was time!), but I hope you'll get to experience the joys of defining your own wonderful, weird types later down the road.

これは、演算子のオーバーロードに直接関係しています。

Pythonプログラマが演算子の型に対する動作を定義する場合、`__lt__`、`__setattr__`、`__contains__`など、2つのアンダースコアで始まり終わる特殊な名前を持つメソッドを実装します。一般に、この二重アンダースコア形式に従った名前はPythonにとって特別な意味を持ちます。

したがって、たとえば式`x in [1、2、3]`は、実際にはリスト・メソッド`__contains__`をバックグラウンドで呼び出しています。これは (もっと醜い) `[1、2、3] .__ contains__ (x) `と同じです。

さらに詳しく知りたい場合は、[Pythonの公式ドキュメント](https://docs.python.org/3.4/reference/datamodel.html#special-method-names)を参照してください。このドキュメントでは、これらの特別な「アンダースコア」メソッドについてさらに多くのことが説明されています。

これらのレッスンでは独自の型を定義しません(時間さえあれば!)が、後で独自の素晴らしい、奇妙な型を定義する喜びを体験できることを願っています。

# Your turn!

Head over to **[the final coding exercise](https://www.kaggle.com/kernels/fork/1275190)** for one more round of coding questions involving imports, working with unfamiliar objects, and, of course, more gambling.

# あなたの番よ!

** [the final coding exercise](https://www.kaggle.com/kernels/fork/1275190) **にアクセスして、インポート、なじみのないオブジェクトの操作、そしてもちろんギャンブルに関するコーディングの質問をもう1ラウンド受けてください。

---




*Have questions or comments? Visit the [course discussion forum](https://www.kaggle.com/learn/python/discussion) to chat with other learners.*

---





*ご質問やご意見がありますか?[Course Discussion Forum] (https://www.kaggle.com/learn/python/discussion) にアクセスして、他の学習者とチャットしてください。*